Fix missing dependency on bionic
Without this, the install hook will fail on bionic with
ModuleNotFoundError: No module named 'importlib_resources'

Change-Id: I889b1d0dad15e36a1e06b1436f3632ed6c6233ea